name: amorphie-core-cache-package
on:
  push:
    branches: [ main ]
    paths:
      - 'Amorphie.Core.Cache/**'   
env:
  APP_NAME: amorphiecore.cache

jobs:
  ci-cd-worker-app:
    if: "!startsWith(github.head_ref, 'feature/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Replace NUGET_API_KEY
        run: |
          sed -i -e "s/NUGETORG_TOKEN/${{ secrets.NUGETORG_TOKEN }}/g" Amorphie.Core.Cache/Dockerfile
      - name: Build and push Api
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./Amorphie.Core.Cache
          file: ./Amorphie.Core.Cache/Dockerfile
          push: false
          tags: amorphie-core-cache:${{ github.sha }}
          
